####################### Enigma I Army Configuration #######################

# Plugboard configuration
plugboard:
  connections: "BG CW DZ ET FO HL JQ NR PU VY"

# Rotors configuration
# From left to right
rotors:
  # Left rotor
  - rotor: III
    position: X
    ringoffset: 5
  # Middle rotor
  - rotor: II
    position: K
    ringoffset: 13
  # Right rotor
  - rotor: IV
    position: M
    ringoffset: 7

# Reflector configuration
reflector:
  type: C

# Show debug information during encryption/decryption
debug: false
# Set to null to prompt the user for the message
message: null

###########################################################################

# Alphabet
etw: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

# Rotors wiring and notches
rotorswiring:
  - rotor: I
    wiring: "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
    notch: Q
  - rotor: II
    wiring: "AJDKSIRUXBLHWTMCQGZNPYFVOE"
    notch: E
  - rotor: III
    wiring: "BDFHJLCPRTXVZNYEIWGAKMUSQO"
    notch: V
  - rotor: IV
    wiring: "ESOVPZJAYQUIRHXLNFTGKDCMWB"
    notch: J
  - rotor: V
    wiring: "VZBRGITYUPSDNHLXAWMJQOFECK"
    notch: Z

# Reflector wiring
reflectorswiring:
  - reflector: A
    wiring: "EJMZALYXVBWFCRQUONTSPIKHGD"
  - reflector: B
    wiring: "YRUHQSLDPXNGOKMIEBFZCWVJAT"
  - reflector: C
    wiring: "FVPJIAOYEDRZXWGCTKUQSBNMHL"
